### ISSUE TITLE
Замечание экзамен js

### ISSUE THREAD

**Issue by AndriiLitvin** [CasTroy/CasTroy.github.io#18]
1.
https://validator.w3.org/nu/?doc=http%3A%2F%2FCasTroy.github.io%2FGoIT%2Fmarkup%2FJavaScript%2Fexam%2Fbuild%2Findex.html

```
<form action="" class = "wrapper__log log">
  <label for="login" class = "log__label montserrat-regular">Log in</label>
  <input type="text" placeholder="Sign up" id = 'login' class = "log__input montserrat-regular" autocomplete = "off">
</form>
```

тут поидеи form не нужен
и тут тоже

```
<form action="">
  <input type="submit" value = "step 2" class = "button button--small montserrat-regular">
</form>
```

2.
тут 

```
<figure class="figure">
  <div class="surcle surcle--big">
    <img src="img/bradley.jpg" alt="bradley">
  </div>
  <div class="surcle surcle--small icon-tv"></div>
  <figcaption class="figure__info info">
  <h3 class="info__name montserrat-regular">Bradley Hunter</h3>
  <p class="info__hobby roboto-light">Based in Chicago. Ilove playing tennis and loud music.</p>
  </figcaption>
</figure>
```

внеси `<div class="surcle surcle--small icon-tv"></div>` в блок

```
<figure class="figure">
  <div class="surcle surcle--big">
    <img src="img/bradley.jpg" alt="bradley">
  <div class="surcle surcle--small icon-tv"></div>
  </div>

  <figcaption class="figure__info info">
  <h3 class="info__name montserrat-regular">Bradley Hunter</h3>
  <p class="info__hobby roboto-light">Based in Chicago. Ilove playing tennis and loud music.</p>
  </figcaption>
</figure>
```

3.
![image](https://cloud.githubusercontent.com/assets/13675947/13994863/668cf32a-f12f-11e5-9734-7d3203248c15.png)

и вообще не соответствует макету и вечно одна или несколько картинок не подгружаються, надо пофиксить.

**Comment by CasTroy** [comment]
Андрюха ну я это всё исправил. Жду дальнейших указаний.

**Comment by AndriiLitvin** [comment]
1.
![image](https://cloud.githubusercontent.com/assets/13675947/14064832/5193a85e-f41a-11e5-9527-de2e5bfa34e7.png)
отцентрируй

2.кнопкам добавь какой то ховер
3.
![image](https://cloud.githubusercontent.com/assets/13675947/14064841/a2654328-f41a-11e5-84d9-d58aa7f55bb2.png)
пофиксь шрифты в ие

**Comment by CasTroy** [comment]
Андерй ну я внес изменения. Со шрифтами я не могу проверить никак. У меня в ie тестере 8 нормально почемуто всё отображает. я поменял c .eot на .ttf почему то и ie9 начал отображать их тоже. Вообщем то что я у себя смотрю у меня всё работает, я хз как внеснти изменения когда не вижу результат.

**Comment by AndriiLitvin** [comment]
сделай на плитке cursor: pointer;
по поводу шрифтов подключи гугл фонт если не поможет то просто допиши sans-serif
а вообще

```
@font-face {
    font-family: 'Montserrat-Regular';
    src: url('../fonts/Montserrat-Regular.ttf') format('truetype');
    src: url('../fonts/Montserrat-Regular.eot');
    src: url('../fonts/Montserrat-Regular.woff') format('woff'),
         url('../fonts/Montserrat-Regular.ttf') format('truetype'),
         url('../fonts/Montserrat-Regular.svg') format('svg');
}
```

вот сервис для форматирования шрифтов http://www.font2web.com/
ну в задании можно подключить GoogleFonts

**Comment by AndriiLitvin** [comment]
Зачет
