### ISSUE TITLE
Замечания по работе №6

### ISSUE THREAD

**Issue by AndriiLitvin** [CasTroy/CasTroy.github.io#3]
## http://joxi.ru/8AnVER6uq1k1PA

1)при ховере текст больше на одн пиксель
2)3)4) тени не такие. вот такие будут box-shadow: 2px 4px 5px 0.00px rgba(150, 150, 150, 0.75);
4)8)там формы все заключить в тег form
5)селекты не соответствуют макету бекграунд белый
6) стрелочка синяя.
7)сделать не таблицей 
9)Для разметки нужно использовать новые семантичные теги: header, footer, aside, nav, section, main, figure, figcaption

**Comment by CasTroy** [comment]
Внёс изменения по всем пунктам, единственное с 9 пунктом не совсем понял, но я заменял на новые теги те блоки где было не совсем понятно что это за блоки.

**Comment by AndriiLitvin** [comment]
## http://joxi.ru/L21b6x0F66LxeA

1) тень
2) при ховере текст стает больше на 1 пиксель + он становиться жирным

**Comment by CasTroy** [comment]
Исправил. Добавил тень и изменил текст при ховере. В макете который я качал тени не было.

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
