### ISSUE TITLE
Замечания по экзамену 7-9

### ISSUE THREAD

**Issue by AndriiLitvin** [CasTroy/CasTroy.github.io#4]
сделай с 7 по 9 задание чтоб я мог поставить экзамен

проверять можно при помощи этого плагина https://chrome.google.com/webstore/detail/ripple-emulator-beta/geelfhphabnejjhdalkjhgipohgpdnoc

**Comment by CasTroy** [comment]
я делаю, но мне работа сейчас не позволяет доделать. У меня всеголишь два дня свободных было сделать.

**Comment by AndriiLitvin** [comment]
хорошо. как сделаешь отпиши пожалуйста. либо сюда либо в скайв в личку

**Comment by CasTroy** [comment]
окей

**Comment by CasTroy** [comment]
Андрей, вроде бы как сделал. Жду проверки.

**Comment by AndriiLitvin** [comment]
http://joxi.ru/xAe0gQ1sYpLJq2
1)убрать точку
2) бубквы не такие + на мозиле вообще полупрозрачные
3)линия не тем цветом
4)тут и по всему макету text-shadow
5)6) стрелочки сделай чтоб видно было
7)10) тут активный элемент
8)сделай больше текста для наглядности
9)все буквы верхнего регистра

у тебя не правильно стоят зависимости экранов 320-479(макет 320) 480-767(480) 768-959(768) и 960+

**Comment by CasTroy** [comment]
внёс исправления

**Comment by AndriiLitvin** [comment]
> у тебя не правильно стоят зависимости экранов 320-479(макет 320) 480-767(480) 768-959(768) и 960+

не исправил нужно @media (min-width: 320px) и так все кроме 960

## Экран 768 http://joxi.ru/a2XQzB3Hy19gkA

1)картинки полезли
2)по моему там бордера нет
3)сделать через css а не картинкой

## Экран 480 http://joxi.ru/Vm67Z8QsxD6XY2

1)нет меню
2)3) поправь бекграунд

## Экран 320 http://joxi.ru/5mdMgP7ivkd6l2 

1)нет меню
2)поправь бекграунд
3)нужен отступ

**Comment by AndriiLitvin** [comment]
при больших экранах контент расплывается  добавь контейнер з фиксированой шириной чтоб активировался на больших экранах

## Экран 960 http://joxi.ru/1A5pK7zFKnV5G2 

1)нет треугольника
2)надпись вровень с верхним блоком 
3)З большой буквы и отступы подгони
4)5) сделай отступ и добавь стрелочки.

## Экран 768 

1)http://joxi.ru/12MjzPDS4MZBdA - оно внизу

**Comment by CasTroy** [comment]
Исправил

**Comment by AndriiLitvin** [comment]
вот это не исправил 

> при больших экранах контент расплывается добавь контейнер з фиксированой шириной чтоб активировался на больших экранах

**Comment by CasTroy** [comment]
Добавил

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
